var searchData=
[
  ['client_0',['Client',['../namespace_client.html',1,'']]],
  ['client_3a_3adomain_1',['Domain',['../namespace_client_1_1_domain.html',1,'Client']]],
  ['client_3a_3adomain_3a_3aservices_2',['Services',['../namespace_client_1_1_domain_1_1_services.html',1,'Client::Domain']]],
  ['client_3a_3adomain_3a_3aservices_3a_3agameservice_3',['GameService',['../namespace_client_1_1_domain_1_1_services_1_1_game_service.html',1,'Client::Domain::Services']]],
  ['client_3a_3adomain_3a_3aservices_3a_3agamestoragemanager_4',['GameStorageManager',['../namespace_client_1_1_domain_1_1_services_1_1_game_storage_manager.html',1,'Client::Domain::Services']]],
  ['client_3a_3adomain_3a_3aservices_3a_3agamestoragemanager_3a_3axml_5',['XML',['../namespace_client_1_1_domain_1_1_services_1_1_game_storage_manager_1_1_x_m_l.html',1,'Client::Domain::Services::GameStorageManager']]],
  ['client_3a_3adomain_3a_3aservices_3a_3aistoragemanager_6',['IStorageManager',['../namespace_client_1_1_domain_1_1_services_1_1_i_storage_manager.html',1,'Client::Domain::Services']]],
  ['client_3a_3adomain_3a_3aservices_3a_3aserverservice_7',['ServerService',['../namespace_client_1_1_domain_1_1_services_1_1_server_service.html',1,'Client::Domain::Services']]],
  ['client_3a_3adomain_3a_3aservices_3a_3asettings_8',['Settings',['../namespace_client_1_1_domain_1_1_services_1_1_settings.html',1,'Client::Domain::Services']]],
  ['client_3a_3adomain_3a_3aservices_3a_3asettings_3a_3agamesettingsservice_9',['GameSettingsService',['../namespace_client_1_1_domain_1_1_services_1_1_settings_1_1_game_settings_service.html',1,'Client::Domain::Services::Settings']]],
  ['client_3a_3adomain_3a_3aservices_3a_3asettings_3a_3aportsettingsservice_10',['PortSettingsService',['../namespace_client_1_1_domain_1_1_services_1_1_settings_1_1_port_settings_service.html',1,'Client::Domain::Services::Settings']]],
  ['client_3a_3adomain_3a_3atests_11',['Tests',['../namespace_client_1_1_domain_1_1_tests.html',1,'Client::Domain']]],
  ['client_3a_3apresentation_12',['Presentation',['../namespace_client_1_1_presentation.html',1,'Client']]],
  ['client_3a_3apresentation_3a_3ahostbuilders_13',['HostBuilders',['../namespace_client_1_1_presentation_1_1_host_builders.html',1,'Client::Presentation']]],
  ['client_3a_3apresentation_3a_3aservices_14',['Services',['../namespace_client_1_1_presentation_1_1_services.html',1,'Client::Presentation']]],
  ['client_3a_3apresentation_3a_3aservices_3a_3anavigator_15',['Navigator',['../namespace_client_1_1_presentation_1_1_services_1_1_navigator.html',1,'Client::Presentation::Services']]],
  ['client_3a_3apresentation_3a_3aviewmodels_16',['ViewModels',['../namespace_client_1_1_presentation_1_1_view_models.html',1,'Client::Presentation']]],
  ['client_3a_3apresentation_3a_3aviews_17',['Views',['../namespace_client_1_1_presentation_1_1_views.html',1,'Client::Presentation']]]
];
